**(2-4):** Run your implementation of the Hebb rule on `data_HL_simple.txt`, and inspect the weights $w$ after every step of the algorithm. Identify the correlational pattern that the algorithm discovers. Are there any positively or negatively correlated features in these data according to the pattern seen in $w$?

In [3]:
import numpy as np
import matplotlib.pyplot as plt

# load data from the text file
data = np.loadtxt('data_HL_simple.txt', usecols=range(5))
print(data[1:5,:])

# we need a vector of 5 parameters
w = np.random.normal(0, 0.5, 5)

print("initial weights")
print(w)

# learning rate; don't change the learning rate epsilon when you are working on questions 2 and 3, unless you really know what you are doing. You may want to make the learning rate dependent on the epoch number to converge to a stable solution.
epsilon = 0.01

num_iterations = 6

update = 0
# we can do a fixed number of iterations because the simple Hebb rule won't converge
for i in range(num_iterations):
    for x in data:

        # TODO: add your code here; note that "epsilon"
        # is defined above and it should be used here;
        # don't change its default value in this question.

        y = np.dot(x,w)
        delta_w = epsilon*y*x

        w = w+delta_w
        
        update = update + 1
        if update % 10 == 0:
            # print every 10th update
            print("\tCurrent input: " + str(x))
            # print the weights for every x to see how they are evolving
            print("New Weights:\n" + str(w))

# the final weights
print(w)


[[-1.  0. -1. -1.  1.]
 [-1. -1. -1. -1.  1.]
 [ 1.  0.  1.  1. -1.]
 [ 0. -1.  0.  0.  0.]]
initial weights
[-0.75274198  0.47185075  0.17669483 -0.17238758 -0.74879497]
	Current input: [0. 0. 0. 0. 0.]
New Weights:
[-0.74666373  0.49456929  0.21123663 -0.13784577 -0.78333677]
	Current input: [-1.  0. -1. -1.  1.]
New Weights:
[-0.75577297  0.5089104   0.2459072  -0.1031752  -0.81800734]
	Current input: [0. 1. 0. 0. 0.]
New Weights:
[-0.76841783  0.51397529  0.28610095 -0.06298145 -0.85820109]
	Current input: [ 0.  0.  1.  1. -1.]
New Weights:
[-0.81847108  0.54832845  0.38246186  0.03337946 -0.954562  ]
	Current input: [ 1.  1.  1.  1. -1.]
New Weights:
[-0.8127617   0.55875029  0.46476616  0.11568375 -1.0368663 ]
	Current input: [0. 0. 0. 0. 0.]
New Weights:
[-0.77049278  0.60319549  0.56538831  0.2163059  -1.13748844]
	Current input: [-1.  0. -1. -1.  1.]
New Weights:
[-0.75498895  0.63381081  0.65707259  0.30799018 -1.22917273]
	Current input: [0. 1. 0. 0. 0.]
New Weights:
[-0.765

**(3-4):** The next step requires coding. Extend the code that implements simple Hebbian learning above and implement Oja's rule to learn one principal component for these data. We are interested in exactly one principal component in this exercise. Your implementation of Oja's rule should appear in the Python block below.

In [4]:
# Implement Oja's rule here extending your previous implementation
# of the simple Hebb rule. Note that this question on Oja's rule
# uses a different dataset. So, don't forget to change the dataset
# after you have copied the code to this block.



# load data from the text file
data = np.loadtxt('data_HL_simple.txt', usecols=range(5))
print(data[1:5,:])

# we need a vector of 5 parameters
w = np.random.normal(0, 0.5, 5)

print("initial weights")
print(w)

# learning rate; don't change the learning rate epsilon when you are working on questions 2 and 3, unless you really know what you are doing. You may want to make the learning rate dependent on the epoch number to converge to a stable solution.
epsilon = 0.01

num_iterations = 6

update = 0
# we can do a fixed number of iterations because the simple Hebb rule won't converge
for i in range(num_iterations):
    for x in data:

        # TODO: add your code here; note that "epsilon"
        # is defined above and it should be used here;
        # don't change its default value in this question.

        y = np.dot(x,w)
        delta_w = epsilon*(x*y-y*y*w)

        w = w+delta_w
        
        update = update + 1
        if update % 10 == 0:
            # print every 10th update
            print("\tCurrent input: " + str(x))
            # print the weights for every x to see how they are evolving
            print("New Weights:\n" + str(w))

# the final weights
print(w)


# do PCA and show the data in 1D
plt.figure(2)
pca = PCA(n_components=1)
# fit the model parameters
pca.fit(data)
print("all principal components:")
print(pca.components_)
# project the data to the new dimension
data_pca = pca.transform(data)
# a vector of zeros for the scatter plot
yaxis = np.zeros(data_pca.shape[0])
plt.scatter(data_pca[:,0], yaxis)
plt.show() 


[[-1.  0. -1. -1.  1.]
 [-1. -1. -1. -1.  1.]
 [ 1.  0.  1.  1. -1.]
 [ 0. -1.  0.  0.  0.]]
initial weights
[-0.37397226 -0.8479258   0.27563584 -0.30436486  0.78693894]
	Current input: [0. 0. 0. 0. 0.]
New Weights:
[-0.37810345 -0.77866597  0.15133444 -0.35119272  0.76930702]
	Current input: [-1.  0. -1. -1.  1.]
New Weights:
[-0.38608321 -0.73456464  0.07227123 -0.37184462  0.74135935]
	Current input: [0. 1. 0. 0. 0.]
New Weights:
[-0.38094074 -0.7127951   0.02602661 -0.38358669  0.72439449]
	Current input: [ 0.  0.  1.  1. -1.]
New Weights:
[-0.3349736  -0.66318382 -0.0564315  -0.42224089  0.72660281]
	Current input: [ 1.  1.  1.  1. -1.]
New Weights:
[-0.33447137 -0.60342161 -0.12997693 -0.4468358   0.71046976]
	Current input: [0. 0. 0. 0. 0.]
New Weights:
[-0.33623349 -0.53347734 -0.21281614 -0.46987029  0.68374532]
	Current input: [-1.  0. -1. -1.  1.]
New Weights:
[-0.34045132 -0.49749214 -0.25814361 -0.47860606  0.66203595]
	Current input: [0. 1. 0. 0. 0.]
New Weights:
[-0.326

NameError: name 'PCA' is not defined

<Figure size 640x480 with 0 Axes>

**(3-5):** Run your implementation of Oja's rule on `data_two_groups.txt`. Use the vector of parameters $w$ that you will obtain using Oja's rule to project the original five-dimensional data into 1 dimension defined by $w$. The image that you will obtain should be similar to the one produced by PCA in `sklearn` above. The images may be identical if you have run Oja's rule until convergence, but this is not guaranteed. This step will allow you to see very clearly how a low dimensional representation (and hence data compression) can be achieved using Hebbian learning/Oja's rule or PCA.

In [ ]:
# Implement Oja's rule here extending your previous implementation
# of the simple Hebb rule. Note that this question on Oja's rule
# uses a different dataset. So, don't forget to change the dataset
# after you have copied the code to this block.

import numpy as np

# load data from the text file
data = np.loadtxt('data_two_groups.txt', usecols=range(5))
print(data[1:5,:])

# we need a vector of 5 parameters
w = np.random.normal(0, 0.5, 5)

print("initial weights")
print(w)

# learning rate; don't change the learning rate epsilon when you are working on questions 2 and 3, unless you really know what you are doing. You may want to make the learning rate dependent on the epoch number to converge to a stable solution.
epsilon = 0.01

num_iterations = 6

update = 0
# we can do a fixed number of iterations because the simple Hebb rule won't converge
for i in range(num_iterations):
    for x in data:

        # TODO: add your code here; note that "epsilon"
        # is defined above and it should be used here;
        # don't change its default value in this question.

        y = np.dot(x,w)
        delta_w = epsilon*(x*y-y*y*w)

        w = w+delta_w
        
        update = update + 1
        if update % 10 == 0:
            # print every 10th update
            print("\tCurrent input: " + str(x))
            # print the weights for every x to see how they are evolving
            print("New Weights:\n" + str(w))

# the final weights
print(w)


# do PCA and show the data in 1D
plt.figure(2)
pca = PCA(n_components=1)
# fit the model parameters
pca.fit(data)
print("all principal components:")
print(pca.components_)
# project the data to the new dimension
data_pca = pca.transform(data)
# a vector of zeros for the scatter plot
yaxis = np.zeros(data_pca.shape[0])
plt.scatter(data_pca[:,0], yaxis)
plt.show() 


**(1-2):** In the above code, identify Python variables that correspond to the symbol $y_j$ in our lecture notes. What is the range of $j$ in this example? How does the number of values of $y_j$ relate to the number of data examples?

In [ ]:
# Implement Oja's rule here extending your previous implementation
# of the simple Hebb rule. Note that this question on Oja's rule
# uses a different dataset. So, don't forget to change the dataset
# after you have copied the code to this block.

import numpy as np

# load data from the text file
data = np.loadtxt('data_two_groups.txt', usecols=range(5))
print(data[1:5,:])

# we need a vector of 5 parameters
w = np.random.normal(0, 0.5, 5)

print("initial weights")
print(w)

# learning rate; don't change the learning rate epsilon when you are working on questions 2 and 3, unless you really know what you are doing. You may want to make the learning rate dependent on the epoch number to converge to a stable solution.
epsilon = 0.01

num_iterations = 6

update = 0
# we can do a fixed number of iterations because the simple Hebb rule won't converge
for i in range(num_iterations):
    for x in data:

        # TODO: add your code here; note that "epsilon"
        # is defined above and it should be used here;
        # don't change its default value in this question.

        y = np.dot(x,w)
        delta_w = epsilon*(x*y-y*y*w)

        w = w+delta_w
        
        update = update + 1
        if update % 10 == 0:
            # print every 10th update
            print("\tCurrent input: " + str(x))
            # print the weights for every x to see how they are evolving
            print("New Weights:\n" + str(w))

# the final weights
print(w)


# do PCA and show the data in 1D
plt.figure(2)
pca = PCA(n_components=1)
# fit the model parameters
pca.fit(data)
print("all principal components:")
print(pca.components_)
# project the data to the new dimension
data_pca = pca.transform(data)
# a vector of zeros for the scatter plot
yaxis = np.zeros(data_pca.shape[0])
plt.scatter(data_pca[:,0], yaxis)
plt.show() 


**(3-1)** Compute `data_rec`, which is the reconstruction of the original data from its compressed 1D representation that is stored in `data_pca`.

In [ ]:
# Implement Oja's rule here extending your previous implementation
# of the simple Hebb rule. Note that this question on Oja's rule
# uses a different dataset. So, don't forget to change the dataset
# after you have copied the code to this block.

import numpy as np

# load data from the text file
data = np.loadtxt('data_two_groups.txt', usecols=range(5))
print(data[1:5,:])

# we need a vector of 5 parameters
w = np.random.normal(0, 0.5, 5)

print("initial weights")
print(w)

# learning rate; don't change the learning rate epsilon when you are working on questions 2 and 3, unless you really know what you are doing. You may want to make the learning rate dependent on the epoch number to converge to a stable solution.
epsilon = 0.01

num_iterations = 6

update = 0
# we can do a fixed number of iterations because the simple Hebb rule won't converge
for i in range(num_iterations):
    for x in data:

        # TODO: add your code here; note that "epsilon"
        # is defined above and it should be used here;
        # don't change its default value in this question.

        y = np.dot(x,w)
        delta_w = epsilon*(x*y-y*y*w)

        w = w+delta_w
        
        update = update + 1
        if update % 10 == 0:
            # print every 10th update
            print("\tCurrent input: " + str(x))
            # print the weights for every x to see how they are evolving
            print("New Weights:\n" + str(w))

# the final weights
print(w)


# do PCA and show the data in 1D
plt.figure(2)
pca = PCA(n_components=1)
# fit the model parameters
pca.fit(data)
print("all principal components:")
print(pca.components_)
# project the data to the new dimension
data_pca = pca.transform(data)
# a vector of zeros for the scatter plot
yaxis = np.zeros(data_pca.shape[0])
plt.scatter(data_pca[:,0], yaxis)
plt.show() 


This question will require the students to engage with the scientific literature. The challenge is to compare the Delta Rule with the Perceptron learning algorithm. The comparison should highlight two differences of both methods. The differences can be related to both how these algorithms work and the properties of the learned models. A technical explanation is required, that is, every difference must be explained using technical terms. Cite the sources that will be used to answer this question. Use books or peer-reviewed scientific papers published in journals or conference-proceedings (blogs and websites are not in this category).

The Delta Rule and the Perceptron learning algorithm are both algorithms used for training artificial neural networks. Here are two key differences between these two methods:

1. **Learning Rule:**
   - **Delta Rule (Widrow-Hoff Rule):** The Delta Rule is a generalization of the Perceptron learning algorithm. It is used for updating the weights of connections in a neural network during supervised learning. Unlike the Perceptron learning algorithm, which only updates the weights based on the error in the output, the Delta Rule takes into account the continuous nature of the output. It uses the gradient descent approach to minimize the error by adjusting the weights in the direction of the steepest decrease in the error function. The Delta Rule considers the actual output of the neuron and aims to reduce the difference between the predicted and target values.
  
   - **Perceptron Learning Algorithm:** The Perceptron learning algorithm, on the other hand, is a binary classifier used for supervised learning of binary linear classifiers. It updates the weights based on the error in the predicted output compared to the target output. If the predicted output is correct, no adjustment is made. However, if there is a misclassification, the weights are updated to move the decision boundary in the direction that corrects the error. The Perceptron learning algorithm is specifically designed for binary classification tasks and is not well-suited for problems where the output is continuous.

2. **Model Representation:**
   - **Delta Rule:** The Delta Rule is commonly used for training multi-layer perceptrons, which are neural networks with one or more hidden layers. It allows for the learning of complex relationships between inputs and outputs by adjusting the weights in each layer. The Delta Rule is well-suited for problems where the output is a continuous function of the inputs, making it suitable for regression tasks.

   - **Perceptron Learning Algorithm:** The Perceptron learning algorithm is primarily used for training single-layer perceptrons, where there is only one layer of weights connecting the input to the output. The decision boundary generated by the Perceptron is a hyperplane, and it is particularly effective for linearly separable binary classification problems. The Perceptron learning algorithm is limited in its ability to learn non-linear relationships between inputs and outputs, as it can only produce linear decision boundaries.

In summary, the Delta Rule and the Perceptron learning algorithm differ in their learning rules, with the Delta Rule incorporating gradient descent for continuous output adjustment, and the Perceptron algorithm using a simple update rule for binary classification. Additionally, the Delta Rule is more versatile, being applicable to multi-layer perceptrons and regression tasks, while the Perceptron is limited to single-layer perceptrons and binary classification with linear decision boundaries.